# Generated by Django 5.2.8 on 2025-11-22 14:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EquipmentDataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("original_filename", models.CharField(max_length=255)),
                ("csv_file", models.FileField(upload_to="uploads/")),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("avg_flowrate", models.FloatField(blank=True, null=True)),
                ("avg_pressure", models.FloatField(blank=True, null=True)),
                ("avg_temperature", models.FloatField(blank=True, null=True)),
                ("type_distribution", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
